# WorldDownloader Serverside Companion configuration file.
# 
# There are permissions that override each of these settings, by the name of
# "wdl.overrideXXX".  They are given to ops by default.

wdl: 
  # Whether the client can use features of WDL that are from newer versions
  # than this plugin is aware of (essentially, this provides a default that
  # is used with unrecognized features).
  canDoNewThings: true
  
  # Whether players are allowed to download the world in general.  If false
  # they aren't allowed (the mod is fully disabled).
  canDownloadInGeneral: true
  
  # The distance from a player that WDL can save chunks.  Use this to limit
  # the area a player can download.  If set to -1, the value for the server
  # in the server config ("view-distance") is used.  HOWEVER, this does not
  # apply when a player is allowed to cache chunks.  When the below setting
  # is set to true, this value is ignored!  (In which case the server value
  # ("view-distance") is used.)
  saveRadius: -1
  
  # Whether a player can cache chunks as they move.  In essence, this means
  # that if the value is true, the player can download the entire map while
  # moving about, but if false, the player will only save the nearby chunks
  # when they stop download.  This doesn't really stop a player from saving
  # the entire map (they could still combine the parts if they wanted), but
  # it will be far harder for a player to do so.  IMPORTANT: If this is set
  # to true, the saveRadius setting is IGNORED!
  canCacheChunks: true
  
  # Whether or not a player can save entities in the map.  This controls if
  # a player can save the location, appearance, inventory contents, and any
  # other information about an animal, monster, or other thing.
  canSaveEntities: true
  
  # Whether a player can save all tile entities as they move about the map.
  # Tile entities (officially, "Block Entities") store additional meta-data
  # for blocks, such as sign text, chest items, and banner patterns.  There
  # are two types that matter to WDL: Ones that have their data sent to the
  # client automatically (such as signs and banners) and ones that need the
  # player to manually open them (containers, such as chests).  For the 2nd
  # group, the setting "wdl.canSaveContainers" must also be true for saving
  # to be allowed. 
  canSaveTileEntities: true
  
  # Whether a player can save containers that require opening to save their
  # contents, such as chests.  For this setting to be meaningful, the value
  # of "wdl.canSaveTileEntities" must be true.  
  canSaveContainers: true
  
  # Whether entity tracking ranges should be sent to the player.  These are
  # obtained from spigot's settings if spigot is installed.  WDL needs this
  # data to correctly identify wheter an entity just went out of a player's
  # range or if it was killed.  If the value is set to false, or the server
  # doesn't use spigot, WDL uses Minecraft's default values.  (These ranges
  # are set in spigot.yml.  Look for entity-tracking-range in the per-world
  # settings.)  If the player cannot save entities, this data is ignored.
  sendEntityRanges: true

  # Per-world configuration goes here.  If a value isn't specified in world
  # world configuration, it uses the default values above.  World names are
  # based off of the folder name.
  per-world: 
    someMinigameWorld: 
      canDownloadInGeneral: false