name: WDLCompanion
main: wdl.WDLCompanion
version: 0.0.1
author: Pokechu22
description: |
  This plugin provides a set of permissions that control what WorldDownloader
  (a mod that downloads a Minecraft world on a server; also known as WDL) may
  download.

permissions: 
  wdl.overrideCanDownloadInGeneral: 
    default: op
    description: |
      If a player has this permission, they are allowed to download the world
      regardless of the value of "wdl.canDownloadInGeneral" in the config.
  wdl.overrideSaveRadius: 
    default: op
    description: |
      If a player has this permission, they are allowed to download chunks at
      the full server chunk view distance regardless of what the config value
      is for "wdl.saveRadius". 
  wdl.overrideCanCacheChunks: 
    default: op
    description: |
      If a player has this permission, they are allowed to cache chunks (thus
      allowing them to save the entire map easily) regardless of the value of
      "wdl.canCacheChunks" in the config.
  wdl.overrideCanSaveEntities: 
    default: op
    description: |
      If a player has this permission, they are allowed to save entities such
      as animals, monsters, and minecart chests throughout the map regardless
      of the value of the config setting "wdl.canSaveEntities".
  wdl.overrideCanSaveTileEntities: 
    default: op
    description: |
      If a player has this permission, they are allowed to save tile entities
      (additional metadata about blocks such as sign text, chest contents, or
      banner appearance) as they move about the world, regardless of what the
      config's setting "wdl.canSaveTileEntities" says.  This only covers tile
      entities that do not require a player to open a GUI to receive the data
      (so chests and similar containers require a second permission, which is
      useless without this one -- "wdl.overrideCanSaveContainers").
  wdl.overrideCanSaveContainers: 
    default: op
    description: |
      If a player has both this permission and the more general permission of
      "wdl.overrideCanSaveContainers", they can save the contents of all tile
      entities that require opening to load the contents (containers) such as
      chests, furnaces, hoppers, brewing stands, and beacons, even if such is
      disabled in the config with "wdl.canSaveContainers" set to "false".